package caiyunc.file.db.mapper;

import caiyunc.file.db.domain.LitemallStorage;

public interface LitemallStorageMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_storage
     *
     * @mbg.generated
     */
    int insert(LitemallStorage record);
}