server:
  port: 9000


aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI4G3LQ3cUEoW3GxnaX6Hv
    accessKeySecret: 0J6lxgyjTMIJASTTfJXUNMRPNmMb0g
    bucketName: caiyunc-app-files


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://193.112.11.62:3306/litemall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: caiyunC2020


mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: caiyunc.file.db.domain